# Generated by Django 4.1.5 on 2023-03-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
