# Generated by Django 4.1.5 on 2023-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
